name: Release Images
on:
  workflow_dispatch: {}
  release:
    types: [released]


# github.event context is only available when the workflow gets triggered by a release event. Therefore, commenting the below
# section and add an additional step of fething the required details explicitly to make the workflow work with manual triggers

#env:
#  # Setting up workflow level environment varibles to make them available in both jobs
#  # The values are extracted from the github.event context, which is automatically availble when a release a created.
#  RELEASE_VERSION: ${{ github.event.release.name }}
#  SOURCE_CODE_URL: ${{ github.event.release.zipball_url }}
#  BRANCH: ${{ github.event.release.target_commitish }}


jobs:
  release-images:
    runs-on: ubuntu-18.04 
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: Build Project
        run: cd registry && make SKIP_TESTS=true BUILD_FLAGS='-Dmaven.wagon.httpconnectionManager.maxTotal=30 -Dmaven.wagon.http.retryHandler.count=5' build-all

      - name: Build The Images For Docker.io
        run: cd registry && ./.github/scripts/build-images.sh ${BRANCH} docker.io release ${RELEASE_VERSION} 

      - name: List All Docker Images
        run: docker images
      
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          
      - name: Push The Images To Docker.io 
        run: cd registry && ./.github/scripts/push-images.sh ${BRANCH} docker.io release ${RELEASE_VERSION}
        
      - name: Build The Images For Quay.io
        run: cd registry && ./.github/scripts/build-images.sh ${BRANCH} quay.io release ${RELEASE_VERSION}

      - name: List All Docker Images
        run: docker images
          
      - name: Login to Quay.io Registry
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" Quay.io
          
      - name: Push The Images To Quay.io 
        run: cd registry && ./.github/scripts/push-images.sh ${BRANCH} quay.io release ${RELEASE_VERSION}
          
      - name: Push The Images To Quay.io 
        run: cd registry && ./.github/scripts/push-images.sh ${BRANCH} quay.io release ${RELEASE_VERSION}
